apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: db
  namespace: instavote
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "12.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: instavote
  values:
    auth:
      database: postgres
      username: postgres
    primary:
      persistence:
        enabled: false
