apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: result
  namespace: instavote
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/charts/result
      sourceRef:
        kind: GitRepository
        name: instavote
        namespace: instavote
  values:
    replicaCount: 1
    service:
      type: LoadBalancer
      port: 80
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
