apiVersion: v1
kind: Service
metadata:
  name: vote
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
